### PR TITLE
feat(certmanager): use caBundle when certmanager is disabled

### PR DESCRIPTION
**Pull request by idrissneumann**

### CODE REVIEW

**Comment by igorcoding** [comment]
Hello! Thank you for the contribution! Looks great.
Could you please add a small description entry to CHANGELOG.md for the update?

**Comment by idrissneumann** [comment]
Thanks for your feedback

> Could you please add a small description entry to CHANGELOG.md for the update?

Yeah of course :) (in progress)

**Comment by idrissneumann** [comment]
Done :)

**Comment by igorcoding** [comment]
Awesome!

**Pull request merged**
